{
 "title": "CDP - Log Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "cdp,rabbitmq-system" },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {}
   },
   { "name": "log_level", "label": "log_level", "query": "ERROR,WARN,INFO,DEBUG" }
  ]
 },
 "panels": [
  {
   "title": "CDP $log_level logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", pod=~\"$Pod\"} |~ \"(?i)$log_level\""
    }
   ]
  },
  {
   "title": "$log_level logs count by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (pod) (count_over_time({namespace=\"$namespace\"} |~ \"(?i)$log_level\" [5m]))"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "All logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=\"$namespace\", pod=~\"$Pod\"}"
      }
     ]
    }
   ]
  }
 ]
}